title: The Re Project
# description: 

remote_theme: "jekyll/minima@c6e74bb"

# github 如果未使用4.0 jeklly，无法识别本地配置 https://github.com/jekyll/jekyll/issues/7971
minima:

  nav_pages:
    - about.md

  social_links:
    - title: 小红书
      icon: address-card
      url: "https://www.xiaohongshu.com/user/profile/6073f800000000000100ba82"